service: app

runtime: nodejs12

# env_variables:
#   clientId: "869656362729-2ikbgfuvtdp96f08usqb28kv68mnluik.apps.googleusercontent.com"
#   secret: "7YJHTkLpHUgHa6YsKU6IY_8k"
#   NODE_ENV: "production"
#   baseURL: 'https://www.personabilities.com'
#   sendApi: "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

env_variables:
  clientId: "592907867622-j13ulkpncujj844httelda6835e8i0bo.apps.googleusercontent.com"
  secret: "AW68HZc3uPh6J4_gPn307k8q"
  NODE_ENV: "app"
  baseURL: 'https://app.personabilities.com'
  sendApi: "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"
  GCLOUD_STORAGE_BUCKET: "us.artifacts.model-axe-273818.appspot.com"

handlers: 
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: "301"